#!/bin/bash

dotnet publish Jellyfin.Plugin.BetaSeries -c Release -o ./publish && \
scp ./publish/Jellyfin.Plugin.BetaSeries.dll root@192.168.1.120:/var/lib/jellyfin/plugins/BetaSeries/ && \
ssh root@192.168.1.120 "rm -f /var/lib/jellyfin/plugins/BetaSeries/Jellyfin.Plugin.Template.dll && chown -R jellyfin:jellyfin /var/lib/jellyfin/plugins/BetaSeries && systemctl restart jellyfin"

